title: Jekyll Fancy Tables
remote_theme: pages-themes/minimal@v0.2.0

repository: RichDom2185/jekyll-fancy-tables
markdown: kramdown

# TODO: logo: assets/img/logo.png
description: A pure Liquid way to generate fancy tables using extended Markdown Syntax.

plugins:
  - jekyll-remote-theme
